export function getElements() {
    return {
        welcomeScreen: document.getElementById("welcomeScreen"),
        welcomeKicker: document.getElementById("welcomeKicker"),
        welcomeGuestName: document.getElementById("welcomeGuestName"),
        welcomeLead: document.getElementById("welcomeLead"),
        welcomeMessage: document.getElementById("welcomeMessage"),
        welcomeClosingLine: document.getElementById("welcomeClosingLine"),
        welcomeLoader: document.getElementById("welcomeLoader"),
        welcomeReady: document.getElementById("welcomeReady"),
        welcomeProgressText: document.getElementById("welcomeProgressText"),

        mainTitle: document.getElementById("mainTitle"),
        mainSubtitle: document.getElementById("mainSubtitle"),
        heroEyebrow: document.getElementById("heroEyebrow"),
        heroIntroNote: document.getElementById("heroIntroNote"),
        guestName: document.getElementById("guestName"),
        bgOverlay: document.getElementById("bgOverlay"),
        guestExtra: document.getElementById("guestExtra"),

        heroStatusPill: document.getElementById("heroStatusPill"),
        heroEventDate: document.getElementById("heroEventDate"),
        heroEventTime: document.getElementById("heroEventTime"),
        heroVenueName: document.getElementById("heroVenueName"),
        heroVenueAddress: document.getElementById("heroVenueAddress"),
        heroRsvpDeadline: document.getElementById("heroRsvpDeadline"),
        heroRsvpHint: document.getElementById("heroRsvpHint"),
        heroSecondaryAction: document.getElementById("heroSecondaryAction"),

        invitationContent: document.getElementById("invitationContent"),
        sectionNav: document.getElementById("sectionNav"),
        contentPanel: document.getElementById("contentPanel"),

        tabDetails: document.getElementById("tabDetails"),
        tabAccess: document.getElementById("tabAccess"),
        tabGallery: document.getElementById("tabGallery"),
        tabRsvp: document.getElementById("tabRsvp"),
        tabPlaylist: document.getElementById("tabPlaylist"),

        playlistKicker: document.getElementById("playlistKicker"),
        playlistTitle: document.getElementById("playlistTitle"),
        playlistDescription: document.getElementById("playlistDescription"),

        confirmationKidsInfoField: document.getElementById("confirmationKidsInfoField"),
        confirmationKidsInfoLabel: document.getElementById("confirmationKidsInfoLabel"),
        confirmationKidsInfo: document.getElementById("confirmationKidsInfo"),

        panelDetails: document.getElementById("panelDetails"),
        panelAccess: document.getElementById("panelAccess"),
        panelGallery: document.getElementById("panelGallery"),
        panelRsvp: document.getElementById("panelRsvp"),
        panelPlaylist: document.getElementById("panelPlaylist"),

        confirmationSummary: document.getElementById("confirmationSummary"),
        heroPrimaryAction: document.getElementById("heroPrimaryAction"),

        countdownSection: document.getElementById("countdownSection"),
        countdownLabel: document.getElementById("countdownLabel"),
        countdownMessage: document.getElementById("countdownMessage"),
        countdown: document.getElementById("countdown"),
        days: document.getElementById("days"),
        hours: document.getElementById("hours"),
        minutes: document.getElementById("minutes"),
        seconds: document.getElementById("seconds"),

        detailsKicker: document.getElementById("detailsKicker"),
        detailsTitle: document.getElementById("detailsTitle"),
        detailsIntroText: document.getElementById("detailsIntroText"),
        detailsScheduleKicker: document.getElementById("detailsScheduleKicker"),
        detailsScheduleTitle: document.getElementById("detailsScheduleTitle"),
        eventDateText: document.getElementById("eventDateText"),
        eventTimeText: document.getElementById("eventTimeText"),
        accessKicker: document.getElementById("accessKicker"),
        accessTitle: document.getElementById("accessTitle"),
        accessIntroText: document.getElementById("accessIntroText"),
        accessVenueKicker: document.getElementById("accessVenueKicker"),
        accessRouteHint: document.getElementById("accessRouteHint"),
        accessQuickFactsTitle: document.getElementById("accessQuickFactsTitle"),
        accessNotesTitle: document.getElementById("accessNotesTitle"),
        venueName: document.getElementById("venueName"),
        venueAddress: document.getElementById("venueAddress"),
        mapButton: document.getElementById("mapButton"),
        copyAddressButton: document.getElementById("copyAddressButton"),
        calendarButton: document.getElementById("calendarButton"),
        timelineSection: document.getElementById("timelineSection"),
        timeline: document.getElementById("timeline"),

        personalMessage: document.getElementById("personalMessage"),
        accessQuickFacts: document.getElementById("accessQuickFacts"),
        accessNotesSection: document.getElementById("accessNotesSection"),
        parkingInfoBlock: document.getElementById("parkingInfoBlock"),
        parkingInfoList: document.getElementById("parkingInfoList"),
        entryInfoBlock: document.getElementById("entryInfoBlock"),
        entryInfoList: document.getElementById("entryInfoList"),
        recommendationsBlock: document.getElementById("recommendationsBlock"),
        recommendationsList: document.getElementById("recommendationsList"),
        guestTags: document.getElementById("guestTags"),

        rsvpDeadline: document.getElementById("rsvpDeadline"),
        rsvpHelperText: document.getElementById("rsvpHelperText"),
        confirmationClosedNote: document.getElementById("confirmationClosedNote"),
        confirmationForm: document.getElementById("confirmationForm"),
        confirmationCountField: document.getElementById("confirmationCountField"),
        confirmationCount: document.getElementById("confirmationCount"),
        confirmationDietaryRestrictions: document.getElementById("confirmationDietaryRestrictions"),
        confirmationComment: document.getElementById("confirmationComment"),
        confirmationSubmitButton: document.getElementById("confirmationSubmitButton"),
        confirmationFeedback: document.getElementById("confirmationFeedback"),
        confirmationProgress: document.getElementById("confirmationProgress"),
        progressStepStatus: document.getElementById("progressStepStatus"),
        progressStepCount: document.getElementById("progressStepCount"),
        progressStepDetails: document.getElementById("progressStepDetails"),

        gallerySection: document.getElementById("gallerySection"),
        gallery: document.getElementById("gallery"),
        galleryIntroText: document.getElementById("galleryIntroText"),
        galleryHintText: document.getElementById("galleryHintText"),
        galleryCounterLabel: document.getElementById("galleryCounterLabel"),
        galleryCounter: document.getElementById("galleryCounter"),

        playlistSection: document.getElementById("playlistSection"),
        playlistCardTitle: document.getElementById("playlistCardTitle"),
        playlistButton: document.getElementById("playlistButton"),
        playlistHighlightLabel: document.getElementById("playlistHighlightLabel"),
        playlistHighlightSong: document.getElementById("playlistHighlightSong"),
        playlistEmbedWrap: document.getElementById("playlistEmbedWrap"),
        playlistEmbed: document.getElementById("playlistEmbed"),

        footerText: document.getElementById("footerText"),

        errorSection: document.getElementById("errorSection"),
        errorTitle: document.getElementById("errorTitle"),
        errorMessage: document.getElementById("errorMessage"),
        retryButton: document.getElementById("retryButton"),

        tabGift: document.getElementById("tabGift"),
        panelGift: document.getElementById("panelGift"),

        giftTitle: document.getElementById("giftTitle"),
        giftIntro: document.getElementById("giftIntro"),
        giftDataCard: document.getElementById("giftDataCard"),
        giftBankStructured: document.getElementById("giftBankStructured"),
        giftBankData: document.getElementById("giftBankData"),
        giftCopyButton: document.getElementById("giftCopyButton"),
        giftShareButton: document.getElementById("giftShareButton"),
        giftFeedback: document.getElementById("giftFeedback"),

        rsvpIntroText: document.getElementById("rsvpIntroText"),
        confirmationLegend: document.getElementById("confirmationLegend"),
        confirmationYesTitle: document.getElementById("confirmationYesTitle"),
        confirmationYesHint: document.getElementById("confirmationYesHint"),
        confirmationNoTitle: document.getElementById("confirmationNoTitle"),
        confirmationNoHint: document.getElementById("confirmationNoHint"),
        confirmationCountLabel: document.getElementById("confirmationCountLabel"),
        confirmationGuestNamesField: document.getElementById("confirmationGuestNamesField"),
        confirmationGuestNamesLabel: document.getElementById("confirmationGuestNamesLabel"),
        confirmationGuestNamesHelper: document.getElementById("confirmationGuestNamesHelper"),
        confirmationGuestNamesList: document.getElementById("confirmationGuestNamesList"),
        confirmationDietaryLabel: document.getElementById("confirmationDietaryLabel"),
        confirmationCommentLabel: document.getElementById("confirmationCommentLabel"),

        lightbox: document.getElementById("lightbox"),
        lightboxImage: document.getElementById("lightboxImage"),
        lightboxClose: document.getElementById("lightboxClose"),
        lightboxPrev: document.getElementById("lightboxPrev"),
        lightboxNext: document.getElementById("lightboxNext"),
        lightboxCaptionText: document.getElementById("lightboxCaptionText"),
        lightboxCaptionCounter: document.getElementById("lightboxCaptionCounter"),

        mobileStickyRsvp: document.getElementById("mobileStickyRsvp"),
        mobileStickyRsvpTitle: document.getElementById("mobileStickyRsvpTitle"),
        mobileStickyRsvpHint: document.getElementById("mobileStickyRsvpHint"),
        mobileStickyRsvpButton: document.getElementById("mobileStickyRsvpButton"),
        musicToggle: document.getElementById("musicToggle"),
        musicToggleText: document.getElementById("musicToggleText"),
        musicToggleHint: document.getElementById("musicToggleHint"),
        musicToggleStatus: document.getElementById("musicToggleStatus"),
        bgMusic: document.getElementById("bgMusic")
    };
}